# Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

### A1:

Purpose and Advantages of NumPy in Scientific Computing: NumPy enhances Python's capabilities by providing high-performance multi-dimensional arrays and a range of mathematical functions for operating on these arrays.
It supports scientific computing and data analysis by offering tools for efficient numerical computation, which are much faster than Python’s native lists, especially for large data sets.

# Q2.  Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

### A2:

Both functions np.mean() and np.average() compute the mean of an array. 
The key difference is that np.average() allows for weighting each element in the array. You would use np.mean() when you need a simple average, and np.average() when you have a weighted dataset.


In [1]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
mean_value = np.mean(a)
print("Mean value", mean_value)

Mean value 4.0


In [6]:
arr = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 1, 1, 1, 5])
weighted_avg = np.average(arr, weights = weights)
print("Weighted Average", weighted_avg)

Weighted Average 3.888888888888889


# Q3.  Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

### A3:

 You can reverse arrays along different axes using slicing:

For a 1D array: arr[::-1].

For a 2D array (matrix): Reverse it along different axes, i.e Reverse rows (reverse the order of the rows) with arr[::-1] or columns (reverse the order of the columns) with arr[:, ::-1].

In [7]:
import numpy as np

# 1D array

a = np.array([1, 2, 3, 4, 5])
reversed_a = a[::-1]
print("Original array:", a)
print("Reversed array:", reversed_a)

Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]


In [8]:
import numpy as np

# 2D array

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
reversed_row = a[::-1]
print("Original 2D array:\n", a)
print("Reversed rows:\n", reversed_row)

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [9]:
reversed_column = a[:, ::-1]
print("Reversed columns:\n", reversed_column)

Reversed columns:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


# Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

### A4:

Use the dtype attribute (e.g., arr.dtype) to check the data type.

Data types are important for memory efficiency and performance, as NumPy arrays are stored in contiguous memory locations, allowing fast access and modification.

# Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?


### A5:

NumPy’s core object is the ndarray, a homogeneous array object of fixed size. 

Key features include support for multi-dimensional arrays, mathematical operations, and broadcasting. 

Unlike Python lists, ndarrays are more memory efficient and faster due to optimized C-based routines.

# Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.


### A6: 

NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations:

1. NumPy uses fixed data types and contiguous memory allocation and Python lists are more memory-intensive with scattered storage.
2. NumPy supports vectorized operations, allowing entire arrays to be processed without explicit loops, unlike Python lists which require slower iteration.
3. NumPy reduces overhead and supports in-place operations, speeding up tasks like addition and multiplication.
4. NumPy is far more efficient than Python lists for handling large-scale data and complex computations.

# Q7.  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.


### A7: 

vstack() stacks arrays vertically (row-wise) and hstack() stacks arrays horizontally (column-wise).

vstack((a, b)): Stack arrays a and b along rows.

hstack((a, b)): Stack arrays a and b along columns.

In [10]:
import numpy as np
a = np.array([1, 2, 3])

# Vertical stacking
result_vstack = np.vstack((a))
print(result_vstack)

[[1]
 [2]
 [3]]


In [11]:
import numpy as np
b = np.array([1, 2, 3])

# Horizontal stacking
result_hstack = np.hstack((b))
print(result_hstack)

[1 2 3]


# Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

### A8:

fliplr() flips an array left to right (horizontal axis).It flips the array along its second axis (axis 1), which corresponds to columns.

flipud() flips an array upside down (vertical axis). It flips the array along its first axis (axis 0), which corresponds to rows.

In [12]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

result_fliplr = np.fliplr(a)
print(result_fliplr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [13]:
result_flipud = np.flipud(a)
print(result_flipud)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


# Q9.  Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

### A9:

array_split() method splits an array into multiple sub-arrays.It allows uneven splits, where the final sub-array may have fewer elements if the array does not divide evenly.

If the array cannot be evenly divided by the number of splits, the first few sub-arrays will receive an extra element to handle the remainder.

In [14]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])

# Split into 2 parts
result = np.array_split(a, 2)
print(result)

[array([1, 2, 3]), array([4, 5, 6])]


In [15]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Split along axis 1 (columns) into 4 parts
result = np.array_split(b, 4, axis=1)
print(result)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]]), array([], shape=(3, 0), dtype=int32)]


# Q10.  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations.


### A10:

Vectorization allows operations to be applied on entire arrays without explicit loops. Broadcasting enables arithmetic operations between arrays of different shapes by expanding smaller arrays to match the larger shape, both contributing to efficient computation.

Vectorization and broadcasting improve Python speed by eliminating Python loops and function call overhead, while also allowing operations on arrays of varying sizes without additional memory usage.

# Practical Questions:


# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

### A1: 



In [16]:
import numpy as np

# 3x3 array with random integers between 1 and 100
a = np.random.randint(1, 101, size=(3, 3))
print("Original Array")
print(a)

# Interchange rows and columns or transpose the array
transposed_array = a.T
print("\nTransposed Array")
print(transposed_array)

Original Array
[[ 58  43  15]
 [100  84  61]
 [ 97  52  17]]

Transposed Array
[[ 58 100  97]
 [ 43  84  52]
 [ 15  61  17]]


#  2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

### A2:


In [18]:
import numpy as np

# 10 elements (e.g., numbers from 0 to 9)
a = np.arange(10)
print("Original Array")
print(a)

# Reshape the array into a 2x5 array
a_2x5 = a.reshape(2, 5)
print("\nReshaped into 2x5 Array")
print(a_2x5)

# Reshape the array into a 5x2 array
a_5x2 = a_2x5.reshape(5, 2)
print("\nReshaped into 5x2 Array")
print(a_5x2)

Original Array
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 Array
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 Array
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#  3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


### A3:

In [19]:
import numpy as np
a_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the array
a_6x6 = np.pad(a_4x4, pad_width=1, mode='constant', constant_values=0)

print(a_6x6)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.38555483 0.16101127 0.0469808  0.87423395 0.        ]
 [0.         0.34446639 0.85153407 0.32799842 0.10119351 0.        ]
 [0.         0.32797679 0.22499598 0.74627884 0.66890414 0.        ]
 [0.         0.71006635 0.52147749 0.61091885 0.55225075 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#  4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

### A4:

In [20]:
import numpy as np
a = np.arange(10, 61, 5)
print(a)

[10 15 20 25 30 35 40 45 50 55 60]


#  5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.


### A5: 

In [21]:
import numpy as np
a = np.array(['python', 'numpy', 'pandas'])
a_upper = np.char.upper(a)
a_lower = np.char.lower(a)
a_title = np.char.title(a)
print(a_upper)
print(a_lower)
print(a_title)

['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


#  6. Generate a NumPy array of words. Insert a space between each character of every word in the array.


### A6: 

In [22]:
import numpy as np

w = np.array(['Cow', 'Sheep', 'Monkey', 'Dog'])
spaced_w = np.array([' '.join(word) for word in w])
print(spaced_w)

['C o w' 'S h e e p' 'M o n k e y' 'D o g']


#  7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.


### A7:

In [26]:
import numpy as np
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
addition = a + b
subtraction = a - b
multiplication = a * b
division = a / b
print("addition:\n", addition)
print("subtraction:\n" , subtraction)
print("multiplication:\n" , multiplication)
print("division:\n" , division)

addition:
 [[16  9]
 [ 9 12]]
subtraction:
 [[-2  3]
 [ 7 -6]]
multiplication:
 [[63 18]
 [ 8 27]]
division:
 [[0.77777778 2.        ]
 [8.         0.33333333]]


#  8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.


### A8:

In [27]:
import numpy as np
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.


### A9:

In [29]:
import numpy as np
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, 100)

# Find all prime numbers in the array
prime_numbers = np.array([num for num in random_integers if is_prime(num)])

print("Random Integers:\n", random_integers)
print("Prime Numbers in the Array:\n", prime_numbers)

Random Integers:
 [770 239 323  59 994 104 455 227 168 316 817 521  41 705 731  44 695 919
 473 372 790 527 298 935 328 101 881 448 328 247 175 692 609 196 413 129
  60 654 770 435 481 196 950 725 430 258 994  29   2 401 169 845 856 655
 726  94 428 859 564 578 346 213 556 747 470 467 956 559 955 807 490 317
 250  29 154 729  18 999 933 786 890 758 342 131 338 540 352 564 265 379
  24 498 830 993  69 444 988 252 275 914]
Prime Numbers in the Array:
 [239  59 227 521  41 919 101 881  29   2 401 859 467 317  29 131 379]


# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.


### A10: 

In [33]:
import numpy as np

# temperatures for 30 days (random between 15°C and 35°C)
temps = np.random.randint(15, 36, 30)

# Reshape into 4 weeks of 7 days and calculate averages
weekly_averages = temps[:28].reshape(4, 7).mean(axis=1)

# average of last 2 days
last_avg = temps[28:].mean()

print("Weekly Averages:", weekly_averages)
print("Last 2 Days Average:", last_avg)

Weekly Averages: [24.85714286 22.71428571 25.         28.71428571]
Last 2 Days Average: 23.5
